#ifndef OPE_VERSION_H
#define OPE_VERSION_H

// Do not edit this file directly, edit VERSION file instead
// Version information are automatically generated from VERSION file

#define OPE_VERSION_MAJOR 0
#define OPE_VERSION_MINOR 0
#define OPE_VERSION_PATCH 1
#define OPE_VERSION_STRING "0.0.1"

#define OPE_VERSION_AT_LEAST(major, minor, patch) \
	((OPE_VERSION_MAJOR > (major)) || \
	 (OPE_VERSION_MAJOR == (major) && OPE_VERSION_MINOR > (minor)) || \
	 (OPE_VERSION_MAJOR == (major) && OPE_VERSION_MINOR == (minor) && OPE_VERSION_PATCH >= (patch)))

#endif // OPE_VERSION_H
